### ISSUE TITLE
Using CMAKE on WRF 4.1

### ISSUE THREAD

**Issue by alleniverson794** [WRF-CMake/wrf#12]
Hi,
I just tried to merge WRF 4.1 into WRF-CMake but got a lot of errors.
Question : Will WRF-CMake support 4.1 and new version officially soon ?
Tx

**Comment by dmey** [comment]
We were thinking of doing this next month. Do you have a specific requirement for using 4.1? And if so when would you need it by? We may be able to move this forward a bit if you cannot use 4.0.x for the moment.

**Comment by alleniverson794** [comment]
Thanks very much for you reply. 
No particular requirement but as we decided to migrate from 3.61 to a new version and I prefer cmake building system I was just wandering if, and when, this repo would be updated. No problem for next month,
Thanks for our work.
Allen
