### ISSUE TITLE
Consider only creating tags from the command line

### ISSUE THREAD

**Issue by zbeekman** [WRF-CMake/wrf#21]
As far as I can tell, when you create a tag through the GitHub UI, it creates a dangling commit object. This means that `git describe` doesn't include it when searching through the tags for the current branch or commit.

For example, I have checked out the `WRF-CMake-4.0.3` tag, but `git describe` on d98d1d47d says: `v4.0.3-39-gd98d1d47d`

**Comment by letmaik** [comment]
Thanks for pointing this out, I wasn't aware of that at all. We'll automate our releases in the future and for that a human will create a tag locally, push it, and then run a "release" CI build on it. So your issue would go away in that case.
How about reporting this issue to GitHub support? Seems like something they should fix.

**Comment by zbeekman** [comment]
> How about reporting this issue to GitHub support? Seems like something they should fix.

I have a while back. It's a "feature". They might change their minds w/ additional reports though.
