### ISSUE TITLE
Community guidelines/contributing etc.

### ISSUE THREAD

**Issue by zbeekman** [WRF-CMake/wrf#23]
Part of the JOSS review asks about:

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I'm a bit confused as to how to assess this. I know the eventual plan is, possibly, to integrate this back upstream. But I have yet to pour over upstream's readme document.

I think, at a minimum, you need to include a `CONTRIBUTING.md` file, with a link from the readme that addresses some of this. You could put all of it in the README, of course, but point 1, "contributing to the software", typically has enough text to warrant its own `CONTRIBUTING.md` file. For reporting issues or problems, you could add an issue template or templates, and address this in the README. For 3, "seek support", you could delineate which types of issues should be reported upstream through the usual mechanism, whatever that is, and include any details of how to seek support for the CMake/build system portions, even if that is "no support offered, beyond bug reporting and pull requests".

**Comment by dmey** [comment]
@zbeekman this should now be fixed in https://github.com/WRF-CMake/WRF/commit/126422239268f1f97c1878ee7a429417d84ae9a7. Let me know if you would like to see more changes.

@letmaik are you happy with https://github.com/WRF-CMake/WRF/commit/126422239268f1f97c1878ee7a429417d84ae9a7?

NOTE TO SELF: merge after #24

**Comment by letmaik** [comment]
@dmey Looks good in general, I left some comments about minor things.
