### ISSUE TITLE
Development netcdf-c repo breaks build on Windows

### ISSUE THREAD

**Issue by dmey** [WRF-CMake/wrf#3]
I have fixed the commit for now so that we can build on Windows (see 110d2fb). However this is not ideal and we need to find a better solution for the long-er term.

For reference, the netcdf-c build log can be viewed here: https://ci.appveyor.com/project/WRF-CMake/releases/build/1.0.1/job/91g2eytq43r08hi3#L600

**Comment by letmaik** [comment]
The MinGW related fixes to netcdf-c [will not be part of the next release](https://github.com/Unidata/netcdf-c/pull/1107#pullrequestreview-157076026) unfortunately, so I suggest we create a separate branch not connected to an upstream PR to prevent the branch potentially getting updated by netcdf-c maintainers (which is what happened here and I didn't realize this was even possible).

**Comment by dmey** [comment]
That's fine by me or we could just leave it as it is -- i.e. pointing to 110d2fb.
