### ISSUE TITLE
Add information about re-compilation to install instructions

### ISSUE THREAD

**Issue by andreas-h** [WRF-CMake/wrf#38]
When working with WRF, sometimes one needs to re-compile the code (e.g., after changing some things in the source code).  When changing the Registry, even a full re-compile is necessary (e.g., `./clean -a && ./compile em_real && ./compile wrf`).

From the compilation instructions here, it is unclear to me how this relates to the WRF-CMAKE build system.

Do I always follow the `cmake ... && make install` ?  Or do I have to clean somehow when changing the registry?

This should be added to the documentation.

**Comment by letmaik** [comment]
Please see https://github.com/WRF-CMake/wrf/blob/wrf-cmake/doc/cmake/INSTALL.md#build-and-install-wrf-cmake. There's a point saying:
> - If you change any registry files, then just re-run `make install`.

Is that what you were looking for?

**Comment by andreas-h** [comment]
> Please see https://github.com/WRF-CMake/wrf/blob/wrf-cmake/doc/cmake/INSTALL.md#build-and-install-wrf-cmake [https://github.com/WRF-CMake/wrf/blob/wrf-cmake/doc/cmake/INSTALL.md#build-and-install-wrf-cmake] . There's a point saying:
 >
 >>
 >> * If you change any registry files, then just re-run make install .
 >>
 >>
 >
 > Is that what you were looking for?

Yes that's fine, thank you for pointing out what I was apparently too blind to see :-/

**Comment by letmaik** [comment]
No problem :)
