### ISSUE TITLE
Bug-fix releases

### ISSUE THREAD

**Issue by dmey** [WRF-CMake/wrf#42]
WRF version 4.1.1 and 4.1.2 have been released, do we want to merge these into `wrf-cmake` branch or wait for 4.2.0... If we merge them in and create the releases, it may be a bit confuses if the prebuilt binaries are not releases.

**Comment by letmaik** [comment]
> If we merge them in and create the releases, it may be a bit confuses if the prebuilt binaries are not releases.

I don't understand this.

**Comment by letmaik** [comment]
I would wait for 4.2.0.

**Comment by dmey** [comment]
OK -- let's wait until then
