### ISSUE TITLE
WRF-CMake binary Release 4.1.5 hasn't provide the shared object dependencies

### ISSUE THREAD

**Issue by cofinoa** [WRF-CMake/wrf#47]
**Describe the bug**
I have tested WRF-CMake-4.1.5 binary release:
wrf-cmake-4.1.5-basic_nesting-serial-x64-linux-release.tar.xz
and the `RPATH` in the binary executables are pointing to: $ORIGIN/../app.libs
but no `app.libs` directory it's bundle in the .tar.xz file. 

**To Reproduce**
1. Just download the above release. 
2. Execute a binary (i.e. main/wrf.exe)
3. See error about shared object not found

**Expected behavior**
The dependencies and RPATH should point to `$ORIGIN/.libs`. 
Release wrf-cmake-4.1.4, works!!. 

**System information (please complete the following information):**
 - OS name and version: Ubuntu 18.04
 - Compiler name and version: N/A

**Comment by letmaik** [comment]
Thanks for reporting and including technical details! I fixed it and re-released 4.1.5. Should be all fine now.

**Comment by adjebbar** [comment]
**ERROR runing  WRF-TEB:**
 
When executing the last command (install) I get an error?

BUILD_TYPE=Release

BUILD_MODE=dmpar


cd wrf-teb

mkdir -p build

cd build

cmake -GNinja -DCMAKE_BUILD_TYPE=$BUILD_TYPE \

        -DMODE=$BUILD_MODE \

        -DCMAKE_INSTALL_PREFIX=install ..

ninja install

"""

FAILED: frame/CMakeFiles/frame.dir/module_configure.F.o frame/mod/module_configure.mod frame/mod/module_irr_diag.mod frame/mod/module_scalar_tables.mod
/usr/bin/gfortran  -I../frame  -I../inc -Iinc -I../frame/../arch -I../frame/../external/ioapi_share -I/home/cons/WORK/WRF_model/Build_WRF/LIBRARIES/mpich/include -Iframe/mod -Iexternal/esmf_time_f90/mod -Iexternal/io_int/mod -cpp -fconvert=big-endian -frecord-marker=4  -ffree-line-length-none -DNONSTANDARD_SYSTEM_SUBR  -O3 -Jframe/mod -fPIC   -ffree-form -fpreprocessed -c frame/CMakeFiles/frame.dir/module_configure.F-pp.f -o frame/CMakeFiles/frame.dir/module_configure.F.o
../frame/module_configure.F:330:14:

  330 | ! the grid id's.  In the grid_config_rec the domain-specific information
      |              1
Warning: missing terminating ' character
../frame/module_configure.F:436:35:

  436 | ! developers and are still in user's namelists.
      |                                   1
Warning: missing terminating ' character
gfortran: fatal error: Killed signal terminated program f951
compilation terminated.
ninja: build stopped: subcommand failed.

"""""

Thanks

**Comment by dmey** [comment]
@adjebbar please report this as a new issue at https://github.com/TEB-model/wrf-teb.

**Comment by adjebbar** [comment]
@dmey OK !
