### ISSUE TITLE
ndown.exe is missing

### ISSUE THREAD

**Issue by lengs14** [WRF-CMake/wrf#53]
Hi. I'm new to WRF and CMake and this pre-built binaries really helps me a lot. 
My problem is, when I try to refine the grid as in the tutorial (https://www2.mmm.ucar.edu/wrf/OnLineTutorial/CASES/NestRuns/ndown.php) , I find there is no ndown.exe in the main folder. So I wonder whether ndown in supported in this version of WRF, and are there alternative methods to complete this task?
I use the latest version of the program built for Windows: "wrf-cmake-4.2.2-basic_nesting-serial-x64-windows-release"

**Comment by dmey** [comment]
Thanks for reporting this. Just checked and you are right `ndown.exe` and `tc.exe` are not produced by the CMake version however I am not sure when either of us will have the time to look at this in more details. Can you run a different example?

@letmaik do you remember why we did not include them in https://github.com/WRF-CMake/wrf/blob/wrf-cmake/main/CMakeLists.txt?

**Comment by letmaik** [comment]
> @letmaik do you remember why we did not include them in https://github.com/WRF-CMake/wrf/blob/wrf-cmake/main/CMakeLists.txt?

No specific reason, mostly because we didn't need it ourselves and it's not one of the tools that you absolutely need, compared to `real.exe` for example.
